In [2]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [6]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [14]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
ser1 = Series([0,1,2],index=['T','U','V'])
ser2 = Series([3,4],index=['X','y'])

In [17]:
ser1

T    0
U    1
V    2
dtype: int64

In [18]:
ser2

X    3
y    4
dtype: int64

In [21]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
y    4
dtype: int64

In [27]:
pd.concat([ser1,ser2],axis=1)

D:\Users\gaoxi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
y  NaN  4.0

In [28]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      y    4
dtype: int64

In [32]:
dframe1 = DataFrame(np.random.rand(4,3),columns=['X','Y','Z'],index=['a','b','c','d'])

In [33]:
dframe2 = DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])

In [34]:
dframe1

X         Y         Z
a  0.429649  0.210834  0.274713
b  0.141002  0.242235  0.771108
c  0.531991  0.215472  0.982771
d  0.337862  0.048433  0.166636

In [35]:
dframe2

Y         Q         X
0 -1.680346  0.286513 -0.106364
1  0.685683  0.208386 -1.496895
2  1.531308 -0.894695  0.450711

In [36]:
pd.concat([dframe1,dframe2])

D:\Users\gaoxi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


Q         X         Y         Z
a       NaN  0.429649  0.210834  0.274713
b       NaN  0.141002  0.242235  0.771108
c       NaN  0.531991  0.215472  0.982771
d       NaN  0.337862  0.048433  0.166636
0  0.286513 -0.106364 -1.680346       NaN
1  0.208386 -1.496895  0.685683       NaN
2 -0.894695  0.450711  1.531308       NaN

In [38]:
pd.concat([dframe1,dframe2],ignore_index=True)
#if we don't care about the index, we can get rid of it.

D:\Users\gaoxi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


Q         X         Y         Z
0       NaN  0.429649  0.210834  0.274713
1       NaN  0.141002  0.242235  0.771108
2       NaN  0.531991  0.215472  0.982771
3       NaN  0.337862  0.048433  0.166636
4  0.286513 -0.106364 -1.680346       NaN
5  0.208386 -1.496895  0.685683       NaN
6 -0.894695  0.450711  1.531308       NaN

In [40]:
url = 'http://pandas.pydata.org/pandas-docs/dev/generated/pandas.tools.merge.concat.html'