In [10]:
import numpy as np

In [13]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
a = np.arange(10).reshape(5,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [24]:
arr  = np.arange(50).reshape((10,5))
arr
#arange: 0-49
#reshape: 10 rows 5 columns


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [25]:
arr.T
#Transpose

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [26]:
np.dot(arr.T,arr)

array([[7125, 7350, 7575, 7800, 8025],
       [7350, 7585, 7820, 8055, 8290],
       [7575, 7820, 8065, 8310, 8555],
       [7800, 8055, 8310, 8565, 8820],
       [8025, 8290, 8555, 8820, 9085]])

In [9]:
arr.reshape((-1,1))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35],
       [36],
       [37],
       [38],
       [39],
       [40],
       [41],
       [42],
       [43],
       [44],
       [45],
       [46],
       [47],
       [48],
       [49]])

In [4]:
arr.T
#T: Transposition

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [5]:
np.dot(arr.T,arr)
#dot product

array([[7125, 7350, 7575, 7800, 8025],
       [7350, 7585, 7820, 8055, 8290],
       [7575, 7820, 8065, 8310, 8555],
       [7800, 8055, 8310, 8565, 8820],
       [8025, 8290, 8555, 8820, 9085]])

In [32]:
arr3d = np.arange(50).reshape((5,5,2))
arr3d
#reshape((5,5,2)): five slices five rows, two columns


array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [39]:
arr3d.transpose((1,0,2))


array([[[ 0,  1],
        [10, 11],
        [20, 21],
        [30, 31],
        [40, 41]],

       [[ 2,  3],
        [12, 13],
        [22, 23],
        [32, 33],
        [42, 43]],

       [[ 4,  5],
        [14, 15],
        [24, 25],
        [34, 35],
        [44, 45]],

       [[ 6,  7],
        [16, 17],
        [26, 27],
        [36, 37],
        [46, 47]],

       [[ 8,  9],
        [18, 19],
        [28, 29],
        [38, 39],
        [48, 49]]])

In [31]:
'''
In [26]: x = np.array((((1,2), (3,4) ), ((5,6),(7,8))))
In [27]: x
Out[27]: 
   array([[[1, 2],
           [3, 4]],
          [[5, 6],
           [7, 8]]])
In [28]: x.shape # dimensions of the array
Out[28]: (2, 2, 2)

In [29]: x.sum(axis=0)
Out[29]: 
array([[ 6,  8],   #  [1,5] = 6 [2,6] = 8 [3,7] = 10 [4, 8] = 12
      [10, 12]])
In [31]: x.sum(axis=1)
Out[31]: 
    array([[ 4,  6],   # [1,3] = 4 [2,4] = 6 [5, 7] = 12 [6, 8] = 14
           [12, 14]])
In [33]: x.sum(axis=2) # [1, 2] = 3 [3, 4] = 7 [5, 6] = 11 [7, 8] = 15
Out[33]: 
array([[ 3,  7],
       [11, 15]])

In [77]: x.ndim # number of dimensions of the array
Out[77]: 3
'''

'\nx = np.array((((1,2), (3,4) ), ((5,6),(7,8))))\nx\nOut[27]: \n   array([[[1, 2],\n           [3, 4]],\n          [[5, 6],\n           [7, 8]]])\nx.shape # dimensions of the array\nOut[28]: (2, 2, 2)\n\nx.sum(axis=0)\nOut[29]: \narray([[ 6,  8],   #  [1,5] = 6 [2,6] = 8 [3,7] = 10 [4, 8] = 12\n      [10, 12]])\nx.sum(axis=1)\nOut[31]: \n    array([[ 4,  6],   # [1,3] = 4 [2,4] = 6 [5, 7] = 12 [6, 8] = 14\n           [12, 14]])\nx.sum(axis=2) # [1, 2] = 3 [3, 4] = 7 [5, 6] = 11 [7, 8] = 15\nOut[33]: \narray([[ 3,  7],\n       [11, 15]])\n\nx.ndim # number of dimensions of the array\nOut[77]: 3\n'

In [34]:
arr = np.array ([[1,2,3]])
arr

array([[1, 2, 3]])

In [35]:
arr.swapaxes(0,1)

array([[1],
       [2],
       [3]])