In [1]:
import numpy as np

In [4]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [6]:
np.exp(arr)
#e exponential, e0,e1,e2...

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [9]:
A = np.random.randn(10)
A

array([ 0.75156199,  0.46339685,  0.00910836,  0.63435612, -0.35476282,
        0.06864748, -0.64786937, -1.4859508 , -1.23974025,  2.1655784 ])

In [11]:
B = np.random.rand(10)
B

array([0.59082022, 0.39144724, 0.96401669, 0.99032693, 0.19481192,
       0.62467634, 0.56143054, 0.56698539, 0.3370032 , 0.46676693])

In [12]:
#Binary Functions 
np.add(A,B)

array([ 1.34238221,  0.85484409,  0.97312505,  1.62468305, -0.1599509 ,
        0.69332382, -0.08643883, -0.91896541, -0.90273705,  2.63234533])

In [13]:
np.maximum(A,B)

array([0.75156199, 0.46339685, 0.96401669, 0.99032693, 0.19481192,
       0.62467634, 0.56143054, 0.56698539, 0.3370032 , 2.1655784 ])

In [3]:
website = 'http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'
import webbrowser 
webbrowser.open(website)

True